version: '3.7'

services:
  app:
    build: ./
    image: image-generator
    ports:
      - 80:80
    command: "python app.py"
    volumes:
      - ./images:/image-generator/images
      - ./generated:/image-generator//generated
